### ISSUE TITLE
npm run dev 启动时报错

### ISSUE THREAD

**Issue by vae1314** [lensh/vue-qq#23]
node build/dev-server.js

/arno/ChatDemo/build/dev-server.js:40
  log: () => {}
        ^
SyntaxError: Unexpected token )
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:902:3

npm ERR! vue-qq@1.0.0 dev: `node build/dev-server.js`
npm ERR! Exit status 8
npm ERR!
npm ERR! Failed at the vue-qq@1.0.0 dev script.
npm ERR! This is most likely a problem with the vue-qq package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node build/dev-server.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls vue-qq
npm ERR! There is likely additional logging output above.
npm ERR! System Linux 3.10.0-514.21.2.el7.x86_64
npm ERR! command "/usr/local/bin/node" "/usr/local/bin/npm" "run" "dev"
npm ERR! cwd /arno/ChatDemo
npm ERR! node -v v0.10.26
npm ERR! npm -v 1.4.3
npm ERR! code ELIFECYCLE
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /arno/ChatDemo/npm-debug.log
npm ERR! not ok code 0
这是什么原因？

**Comment by vae1314** [comment]
我在执行npm install时，运行到这步卡住了，是怎么回事？
屏幕打印log如下:
.....
npm http 304 https://registry.npmjs.org/utils-merge/1.0.1
npm http GET https://registry.npmjs.org/thenify-all
npm http 304 https://registry.npmjs.org/setprototypeof/1.1.0
npm http 304 https://registry.npmjs.org/methods

> uws@0.14.5 install /arno/ChatDemo/node_modules/socket.io/node_modules/engine.i                                                      o/node_modules/uws
> node-gyp rebuild > build_log.txt 2>&1 || exit 0

**Comment by lensh** [comment]
node版本的问题，你先升级到v8版本
